language: c
sudo: false
matrix:
  allow_failures:
    - compiler: clang
      env:
        - C_COMPILER='clang-3.9'
        - BUILD_TYPE='release'
        - NAME='clang'
        - VERSION='3.9'

  include:

  - os: linux
    compiler: clang
    addons: &1
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - liblapack-dev
        - clang-3.6
    env:
      - C_COMPILER='clang-3.6'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.6'

  - os: linux
    compiler: clang
    addons: &2
      apt:
        sources:
        - llvm-toolchain-precise-3.9
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - liblapack-dev
        - clang-3.9
    env:
      - C_COMPILER='clang-3.9'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.9'


  - os: linux
    compiler: gcc
    addons: &3
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - liblapack-dev
        - g++-4.9
        - gcc-4.9
    env:
      - C_COMPILER='gcc-4.9'
      - BUILD_TYPE='release'
      - NAME='gcc'
      - VERSION='4.9'

  - os: linux
    compiler: gcc
    addons: &4
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - liblapack-dev
        - g++-6
        - gcc-6
    env:
      - C_COMPILER='gcc-6'
      - BUILD_TYPE='release'
      - NAME='gcc'
      - VERSION=6

#  - os: linux
#    compiler: gcc
#    addons: &5
#      apt:
#        sources:
#        - ubuntu-toolchain-r-test
#        - george-edison55-precise-backports
#        packages:
#        - python3
#        - cmake
#        - cmake-data
#        - libhdf5-serial-dev
#        - liblapack-dev
#        - g++-6
#        - gcc-6
#        - gfortran-6
#    env:
#      - CXX_COMPILER='g++-6'
#      - C_COMPILER='gcc-6'
#      - Fortran_COMPILER='gfortran-6'
#      - BUILD_TYPE='release'
#      - NAME='gcc'
#      - VERSION=6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
before_script:
- cd ${TRAVIS_BUILD_DIR}
- export CC=${C_COMPILER}
- export CTEST_OUTPUT_ON_FAILURE=1
- ${C_COMPILER} --version
- > 
    cmake -Bbuild -H. 
    -DCMAKE_C_COMPILER=${C_COMPILER} 
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} 
    -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/Install
- cd build
- ../.scripts/travis_build.sh
script:
- ls -l
#- python ../.scripts/travis_run_test.py
#- python ../.scripts/travis_print_failing.py
